export const menuItems = [
  { name: "Home", path: "/" },
  { name: "Menu", path: "/menu" },
  { name: "About", path: "/about" },
  { name: "FAQ", path: "/faq" },
  { name: "Blog", path: "/blog" },
  { name: "Contact", path: "/contact" },
];

// Footer Menu items
export const footerMenuItem = [
  { name: "Blog", url: "/blog" },
  { name: "Location", url: "/career" },
  { name: "About Us", url: "/resources" },
  { name: "Reservation", url: "/reservation" },
];

// Footer Links items
export const footerLinkItems = [
  { name: "Privacy Policy", url: "/privacy-policy" },
  { name: "Terms of Services", url: "/terms-of-services" },
  { name: "About Us", url: "/resources" },
  { name: "Reservation", url: "/reservation" },
];

// Social Data
export const socialData = [
  {
    href: "#",
    icon: "proicons:facebook",
    color: "hover:text-[#769bea]",
  },
  {
    href: "#",
    icon: "fe:instagram",
    color: "hover:text-[#e4405f]",
  },
  {
    href: "#",
    icon: "ph:youtube-logo",
    color: "hover:text-[#1DA1F2]",
  },
];

// For Contact
// Card data array
export const contactCardData = [
  {
    icon: "mdi:phone",
    title: "Call Us",
    description: "Our expart team is here to help you from 9am to 5pm.",
    link: "tel:+12404937034",
    linkText: "+1 240-493-7034",
  },
  {
    icon: "mdi:email-outline",
    title: "Email Us",
    description:
      "Send us an email and we'll get back to you within a short time.",
    link: "mailto:ask@redbowlhibachi.com",
    linkText: "ask@redbowlhibachi.com",
  },
  {
    icon: "mdi:map-marker",
    title: "Visit Us",
    description:
      "We are proudly built in USA, serving businesses across all industries.",
    link: "https://www.google.com/search?q=6210+Livingston+Rd%2C+Oxon+Hill%2C+MD+20745%2C+United+States&oq=6210+Livingston+Rd%2C+Oxon+Hill%2C+MD+20745%2C+United+States&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBBzI2NmowajeoAgiwAgHxBRP71jnoWQzv&sourceid=chrome&ie=UTF-8",
    linkText: "Get directions",
    isExternal: true,
  },
];

export const menuData = [
  {
    mainCategory: "Chicken Menu",
    icon: "streamline:chicken-grilled-stream",

    menus: [
      {
        id: "2pc-chicken-combo",
        name: "2PC Chicken Combo",
        price: "$10.99",
        description:
          "2 pieces of crispy fried chicken served with noodles in marinara sauce and grated Parmesan cheese",
        rating: 4.6,
        reviewCount: 87,
        isPopular: true,
        category: "fried-chicken",
        url: "/img/food/chicken/chicken-2pc-combo.jpg",
      },
      {
        id: "3pc-chicken-combo",
        name: "3PC Chicken Combo",
        price: "$12.99",
        description:
          "3 pieces of crispy fried chicken served with noodles in marinara sauce and grated Parmesan cheese",
        rating: 4.7,
        reviewCount: 92,
        isPopular: false,
        category: "fried-chicken",
        url: "/img/food/chicken/chicken-3pc-combo.jpg",
      },
      {
        id: "4pc-wings-combo",
        name: "4PC Wings Combo",
        price: "$12.99",
        description:
          "4 crispy wings served with noodles in marinara sauce and grated Parmesan cheese",
        rating: 4.5,
        reviewCount: 80,
        isPopular: false,
        category: "fried-chicken",
        url: null,
      },
      {
        id: "4pc-chicken-breast-combo",
        name: "4PC Chicken Combo (Breast)",
        price: "$12.99",
        description:
          "4 pieces of chicken breast served with noodles in marinara sauce and grated Parmesan cheese",
        rating: 4.8,
        reviewCount: 100,
        isPopular: true,
        category: "fried-chicken",
        url: "/img/food/chicken/chicken-4pc-combo.jpg",
      },
      {
        id: "leg",
        name: "Leg",
        price: "$2.49",
        description: "Single piece chicken leg",
        rating: 4.2,
        reviewCount: 42,
        isPopular: false,
        category: "fried-chicken",
        url: "/img/food/chicken/chicken-leg.jpg",
      },
      {
        id: "thigh",
        name: "Thigh",
        price: "$2.49",
        description: "Single piece chicken thigh",
        rating: 4.3,
        reviewCount: 45,
        isPopular: false,
        category: "fried-chicken",
        url: "/img/food/chicken/chicken-thigh.jpg",
      },
      {
        id: "wing",
        name: "Wing",
        price: "$2.00",
        description: "Single chicken wing",
        rating: 4.1,
        reviewCount: 30,
        isPopular: false,
        category: "fried-chicken",
        url: "/img/food/chicken/chicken-wing.jpg",
      },
      {
        id: "pearl-sugar-waffle",
        name: "Pearl Sugar Waffle",
        price: "$1.99",
        description: "Sweet pearl sugar waffle",
        rating: 4.0,
        reviewCount: 25,
        isPopular: false,
        category: "fried-chicken",
        url: null,
      },

      // Sandwich
      {
        id: "crispy-chicken",
        name: "Crispy Chicken Sandwich",
        price: "$7.99",
        description: "Crispy Chicken, Pickles, Mayo",
        rating: 4.6,
        reviewCount: 76,
        isPopular: true,
        category: "sandwich",
        url: "/img/food/sandwich/sandwich-CrispyChickenSandwich.jpg",
      },
      {
        id: "honey-hot-chicken",
        name: "Honey Hot Chicken Sandwich",
        price: "$8.99",
        description:
          "Crispy Chicken, House honey hot sauce, Coleslaw, Chipotle sauce",
        rating: 4.7,
        reviewCount: 81,
        isPopular: true,
        category: "sandwich",
        url: "/img/food/sandwich/sandwich-RedHoneyChickenSandwich.jpg",
      },
      {
        id: "red-hot-chicken",
        name: "Red Hot Chicken Sandwich",
        price: "$8.99",
        description:
          "Crispy Chicken, Spicy seasoning, Pickles, Spicy mayo, Chipotle sauce",
        rating: 4.5,
        reviewCount: 66,
        isPopular: false,
        category: "sandwich",
        url: null,
      },

      //  Tenders
      {
        id: "3pc-tender",
        name: "3PC Tender",
        price: "$5.99",
        description: "3 pieces of crispy chicken tenders",
        rating: 4.4,
        reviewCount: 50,
        isPopular: false,
        category: "tenders",
        url: null,
      },
      {
        id: "6pc-tender",
        name: "6PC Tender",
        price: "$10.99",
        description: "6 pieces of crispy chicken tenders",
        rating: 4.6,
        reviewCount: 58,
        isPopular: true,
        category: "tenders",
        url: null,
      },
      {
        id: "12pc-tender",
        name: "12PC Tender",
        price: "$19.99",
        description: "12 pieces of crispy chicken tenders",
        rating: 4.7,
        reviewCount: 65,
        isPopular: true,
        category: "tenders",
        url: null,
      },
      {
        id: "6pc-chicken-bites",
        name: "6PC Chicken Bites",
        price: "$5.99",
        description: "6 pieces of crispy chicken bites",
        rating: 4.3,
        reviewCount: 40,
        isPopular: false,
        category: "tenders",
        url: null,
      },
      {
        id: "12pc-chicken-bites",
        name: "12PC Chicken Bites",
        price: "$10.99",
        description: "12 pieces of crispy chicken bites",
        rating: 4.5,
        reviewCount: 48,
        isPopular: false,
        category: "tenders",
        url: null,
      },
    ],
  },

  {
    mainCategory: "Hibachi Menu",
    icon: "hugeicons:noodles",
    menus: [
      {
        id: "chicken-hibachi",
        name: "Chicken Hibachi",
        price: "$9.99",
        description: "Grilled chicken hibachi served with 2 sides.",
        rating: 4.8,
        reviewCount: 124,
        isPopular: true,
        category: "hibachi",
        url: "/img/food/hebachi/hebachi-ChickenHibachi.jpg",
      },
      {
        id: "beef-hibachi",
        name: "Beef Hibachi",
        price: "$10.99",
        description:
          "Juicy, tender beef hibachi paired with your choice of two delicious sides.",
        rating: 4.7,
        reviewCount: 98,
        isPopular: false,
        category: "hibachi",
        url: "/img/food/hebachi/hebachi-BeefHabachiBowl.jpg",
      },
      {
        id: "shrimp-hibachi",
        name: "Shrimp Hibachi",
        price: "$10.99",
        description: "Juicy shrimp hibachi served with 2 sides.",
        rating: 4.6,
        reviewCount: 87,
        isPopular: false,
        category: "hibachi",
        url: null,
      },
      {
        id: "salmon-hibachi",
        name: "Salmon Hibachi",
        price: "$12.99",
        description: "Grilled salmon hibachi served with 2 sides.",
        rating: 4.9,
        reviewCount: 110,
        isPopular: true,
        category: "hibachi",
        url: null,
      },
      {
        id: "chicken-shrimp-hibachi",
        name: "Chicken & Shrimp Hibachi",
        price: "$12.99",
        description: "Chicken and shrimp hibachi served with 2 sides.",
        rating: 4.7,
        reviewCount: 90,
        isPopular: true,
        category: "hibachi",
        url: null,
      },
      {
        id: "beef-shrimp-hibachi",
        name: "Beef & Shrimp Hibachi",
        price: "$13.99",
        description: "Beef and shrimp hibachi served with 2 sides.",
        rating: 4.8,
        reviewCount: 97,
        isPopular: true,
        category: "hibachi",
        url: "/img/food/hebachi/hebachi-Beef&ShrimpHibachiBowl.jpg",
      },
      {
        id: "salmon-shrimp-hibachi",
        name: "Salmon & Shrimp Hibachi",
        price: "$15.99",
        description: "Salmon and shrimp hibachi served with 2 sides.",
        rating: 4.9,
        reviewCount: 104,
        isPopular: true,
        category: "hibachi",
        url: "/img/food/hebachi/hebachi-ShrimpAndSalmonHibachiCombo.jpg",
      },

      // Sushi
      {
        id: "california-roll",
        name: "California Roll",
        price: "$6.99",
        description: "Crab meat, cucumber, and avocado.",
        rating: 4.5,
        reviewCount: 77,
        isPopular: false,
        category: "sushi",
        url: "/img/food/sushi/sushi-CaliforniaRoll.jpg",
      },
      {
        id: "sriracha-crab-shrimp-roll",
        name: "Sriracha Crab and Shrimp Roll",
        price: "$7.99",
        description: "Spicy crab, grilled shrimp, and spicy mayo.",
        rating: 4.6,
        reviewCount: 81,
        isPopular: true,
        category: "sushi",
        url: null,
      },
      {
        id: "shrimp-tempura-roll",
        name: "Shrimp Tempura Roll",
        price: "$7.99",
        description: "Shrimp tempura, cucumber, and eel sauce.",
        rating: 4.7,
        reviewCount: 84,
        isPopular: true,
        category: "sushi",
        url: "/img/food/sushi/sushi-ShrimpTempuraRoll.jpg",
      },
      {
        id: "salmon-roll",
        name: "Salmon Roll",
        price: "$8.99",
        description: "Fresh salmon, avocado, and spicy mayo.",
        rating: 4.6,
        reviewCount: 79,
        isPopular: false,
        category: "sushi",
        url: "/img/food/sushi/sushi-SalmonRoll.jpg",
      },
      {
        id: "shrimp-medley-roll",
        name: "Shrimp Medley Roll",
        price: "$9.99",
        description:
          "Shrimp tempura, grilled shrimp, cucumber, eel sauce & spicy mayo.",
        rating: 4.8,
        reviewCount: 83,
        isPopular: true,
        category: "sushi",
        url: "/img/food/sushi/sushi-ShrimpMedleyRoll.jpg",
      },
      {
        id: "red-bowl-special-roll",
        name: "Red Bowl Special Roll",
        price: "$10.99",
        description:
          "Spicy crab, cucumber, fresh salmon, avocado & spicy mayo.",
        rating: 4.9,
        reviewCount: 99,
        isPopular: true,
        category: "sushi",
        url: "/img/food/sushi/sushi-RedBowlRiceSpecialRoll.jpg",
      },

      // Bento Box
      {
        id: "chicken-bento",
        name: "Chicken Bento",
        price: "$11.99",
        description:
          "Chicken with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
        rating: 4.6,
        reviewCount: 70,
        isPopular: false,
        category: "bento",
        url: "/img/food/bento/bento-ChickenBentoBox.jpg",
      },
      {
        id: "beef-bento",
        name: "Beef Bento",
        price: "$12.99",
        description:
          "Beef with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
        rating: 4.7,
        reviewCount: 74,
        isPopular: false,
        category: "bento",
        url: "/img/food/bento/bento-BeefBentoBox.jpg",
      },
      {
        id: "shrimp-bento",
        name: "Shrimp Bento",
        price: "$12.99",
        description:
          "Shrimp with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
        rating: 4.6,
        reviewCount: 72,
        isPopular: false,
        category: "bento",
        url: "/img/food/bento/bento-ShrimpBentoBox.jpg",
      },
      {
        id: "salmon-bento",
        name: "Salmon Bento",
        price: "$14.99",
        description:
          "Salmon with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
        rating: 4.8,
        reviewCount: 82,
        isPopular: true,
        category: "bento",
        url: "/img/food/bento/bento-SalmonBentoBox.jpg",
      },
      {
        id: "chicken-shrimp-bento",
        name: "Chicken & Shrimp Bento",
        price: "$14.99",
        description:
          "Chicken & shrimp with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
        rating: 4.7,
        reviewCount: 78,
        isPopular: true,
        category: "bento",
        url: "/img/food/bento/bento-ChickenShrimpBento.jpg",
      },
      {
        id: "beef-shrimp-bento",
        name: "Beef & Shrimp Bento",
        price: "$15.99",
        description:
          "Beef & shrimp with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
        rating: 4.8,
        reviewCount: 85,
        isPopular: true,
        category: "bento",
        url: "/img/food/bento/bento-Beef&ShrimpBentoBox.jpg",
      },
      {
        id: "salmon-shrimp-bento",
        name: "Salmon & Shrimp Bento",
        price: "$17.99",
        description:
          "Salmon & shrimp with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
        rating: 4.9,
        reviewCount: 88,
        isPopular: true,
        category: "bento",
        url: "/img/food/bento/bento-hrimp&SalmonBentoBox.jpg",
      },
    ],
  },

  {
    mainCategory: "Red Bowl Special",
    icon: "hugeicons:dish-01",
    menus: [
      {
        id: "chicken-parmesan",
        name: "Chicken Parmesan",
        price: "$9.99",
        description:
          "Crispy Chicken or Grilled Chicken served with noodles, marinara sauce, and grated Parmesan cheese.",
        rating: 4.7,
        reviewCount: 95,
        isPopular: true,
        category: "parmesan-bowl",
        url: "/img/food/parmisan/parmesanChickenParmesan.jpg",
      },
      {
        id: "shrimp-parmesan",
        name: "Shrimp Parmesan",
        price: "$11.99",
        description:
          "Crispy Shrimp or Grilled Shrimp served with noodles, marinara sauce, and grated Parmesan cheese.",
        rating: 4.8,
        reviewCount: 88,
        isPopular: true,
        category: "parmesan-bowl",
        url: "/img/food/parmisan/parmisan-ShrimpParmesanBowl.jpg",
      },
      {
        id: "meatball-parmesan",
        name: "Meatball Parmesan",
        price: "$11.99",
        description:
          "Meatballs served with noodles, marinara sauce, and grated Parmesan cheese.",
        rating: 4.6,
        reviewCount: 76,
        isPopular: false,
        category: "parmesan-bowl",
        url: "/img/food/parmisan/parmesan_MeatBallParmesan.jpg",
      },
      {
        id: "grilled-salmon-parmesan",
        name: "Grilled Salmon Parmesan",
        price: "$13.99",
        description:
          "Grilled Salmon served with noodles, marinara sauce, and grated Parmesan cheese.",
        rating: 4.9,
        reviewCount: 84,
        isPopular: true,
        category: "parmesan-bowl",
        url: "/img/food/parmisan/parmesan-GrilledSalmonParmesanBowl.jpg",
      },

      //  Smoothie
      {
        id: "sweet-mango",
        name: "Sweet Mango",
        price: "$6.99",
        description: "Fresh mango smoothie.",
        rating: 4.5,
        reviewCount: 45,
        isPopular: false,
        category: "smoothie",
        url: null,
      },
      {
        id: "banana-banana",
        name: "Banana Banana",
        price: "$6.99",
        description: "Double banana smoothie delight.",
        rating: 4.4,
        reviewCount: 42,
        isPopular: false,
        category: "smoothie",
        url: null,
      },
      {
        id: "strawberry-banana",
        name: "Strawberry Banana",
        price: "$6.99",
        description: "Classic strawberry banana smoothie.",
        rating: 4.6,
        reviewCount: 51,
        isPopular: true,
        category: "smoothie",
        url: null,
      },
      {
        id: "pina-colada",
        name: "Pina Colada",
        price: "$7.99",
        description: "Tropical pineapple and coconut smoothie.",
        rating: 4.7,
        reviewCount: 53,
        isPopular: true,
        category: "smoothie",
        url: null,
      },

      //  Mac & Cheese
      {
        id: "mac-cheese",
        name: "Mac & Cheese",
        price: "$5.99",
        description: "Classic cheesy macaroni.",
        rating: 4.4,
        reviewCount: 61,
        isPopular: false,
        category: "mac-n-cheese",
        url: "/img/food/mac/mac_MacAndCheese.jpg",
      },
      {
        id: "mac-chicken",
        name: "Mac & Chicken",
        price: "$7.99",
        description: "Mac & Cheese topped with crispy chicken.",
        rating: 4.6,
        reviewCount: 66,
        isPopular: true,
        category: "mac-n-cheese",
        url: null,
      },
      {
        id: "mac-shrimp",
        name: "Mac & Shrimp",
        price: "$8.99",
        description: "Mac & Cheese topped with shrimp.",
        rating: 4.7,
        reviewCount: 70,
        isPopular: true,
        category: "mac-n-cheese",
        url: null,
      },

      //  Sides
      {
        id: "waffle-fries",
        name: "Waffle Fries",
        price: "$4.49",
        description: "Crispy waffle-cut fries.",
        rating: 4.3,
        reviewCount: 39,
        isPopular: false,
        category: "sides",
        url: "/img/food/side/side-WaffleFries.jpg",
      },
      {
        id: "fried-rice",
        name: "Fried Rice",
        price: "$4.49",
        description: "Flavorful fried rice.",
        rating: 4.5,
        reviewCount: 47,
        isPopular: false,
        category: "sides",
        url: "/img/food/side/side-FriedRice.jpg",
      },
      {
        id: "white-rice",
        name: "White Rice",
        price: "$3.49",
        description: "Steamed white rice.",
        rating: 4.1,
        reviewCount: 34,
        isPopular: false,
        category: "sides",
        url: "/img/food/side/side-whiteRice.jpg",
      },
      {
        id: "noodles",
        name: "Noodles",
        price: "$4.49",
        description: "Savory noodles.",
        rating: 4.4,
        reviewCount: 41,
        isPopular: false,
        category: "sides",
        url: "/img/food/side/side-Noodles.jpg",
      },
      {
        id: "grilled-vegetables",
        name: "Grilled Vegetables",
        price: "$4.49",
        description: "Assorted grilled veggies.",
        rating: 4.5,
        reviewCount: 43,
        isPopular: false,
        category: "sides",
        url: "/img/food/side/side-GrilledVegetables.jpg",
      },
      {
        id: "coleslaw",
        name: "Coleslaw",
        price: "$3.99",
        description: "Creamy coleslaw side.",
        rating: 4.2,
        reviewCount: 33,
        isPopular: false,
        category: "sides",
        url: "/img/food/side/side-Coleslaw.jpg",
      },
      {
        id: "spring-roll",
        name: "4PC Spring Roll",
        price: "$3.99",
        description: "4 crispy vegetable spring rolls.",
        rating: 4.4,
        reviewCount: 38,
        isPopular: false,
        category: "sides",
        url: null,
      },
      {
        id: "dumplings",
        name: "5PC Dumplings",
        price: "$4.49",
        description: "5 savory dumplings.",
        rating: 4.6,
        reviewCount: 44,
        isPopular: false,
        category: "sides",
        url: null,
      },
    ],
  },
];

export const HomeFoodItems = [
  {
    id: "beef-hibachi",
    name: "Beef Hibachi",
    price: "$10.99",
    description:
      "Juicy, tender beef hibachi paired with your choice of two delicious sides.",
    rating: 4.7,
    reviewCount: 98,
    isPopular: false,
    category: "hibachi",
    url: "/img/food/hebachi/hebachi-BeefHabachiBowl.jpg",
  },

  {
    id: "shrimp-bento",
    name: "Shrimp Bento",
    price: "$12.99",
    description:
      "Shrimp with 4pc California roll, 2 spring rolls, 2 dumplings & 2 sides.",
    rating: 4.6,
    reviewCount: 72,
    isPopular: false,
    category: "bento",
    url: "/img/food/bento/bento-ShrimpBentoBox.jpg",
  },
  {
    id: "3pc-chicken-combo",
    name: "3PC Chicken Combo",
    price: "$12.99",
    description:
      "3 pieces of crispy fried chicken served with noodles in marinara sauce and grated Parmesan cheese",
    rating: 4.7,
    reviewCount: 92,
    isPopular: false,
    category: "fried-chicken",
    url: "/img/food/chicken/chicken-3pc-combo.jpg",
  },
];

export const signatureDishMenuItems = [
  {
    title: "Beef Hibachi",
    description:
      "Juicy, tender beef hibachi paired with your choice of two delicious sides.",
    price: "$10.99",
    url: "/img/food/hebachi/hebachi-BeefHabachiBowl.jpg",
  },
  {
    title: "Salmon & Shrimp Hibachi",
    description: "Salmon and shrimp hibachi served with 2 sides.",
    price: "$15.99",
    url: "/img/food/hebachi/hebachi-ShrimpAndSalmonHibachiCombo.jpg",
  },
  {
    title: "3PC Chicken Combo",
    description:
      "3 pieces of crispy fried chicken served with noodles in marinara sauce and grated Parmesan cheese.",
    price: "$12.99",
    url: "/img/food/chicken/chicken-3pc-combo.jpg",
  },

  {
    title: "Beef & Shrimp Hibachi",
    description: "Beef and shrimp hibachi served with 2 sides.",
    price: "$13.99",
    url: "/img/food/hebachi/hebachi-Beef&ShrimpHibachiBowl.jpg",
  },
];
